import sys
from PyQt5.QtWidgets import QApplication, QWidget, QDialog
from MotorSim_GUI import Ui_MainWindow #testGUI() is the name of the class is the code generated by pyqt
# tempFile is the name of the output file made by pyuic

class AppWindow(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow() #testGUI() is the name of the class is the code generated by pyqt
        self.ui.setupUi(self)
        self.show()

app = QApplication(sys.argv)
w = AppWindow()
w.show()
sys.exit(app.exec())
